zeta_zero: 1.
v_remission: -0.046
v_relapse: 0.012
w_shape: 4.69
w_scale: 1653.41
variable: 'visit_every'
n_reps: 100
visit_freqs:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
sigmas:
  - 1.00
n_samples:
  - 500
